### PR TITLE
Cleanup worker directories when finished

### PR DESCRIPTION
**Pull request by TomAugspurger**
This cleans up worker directories when workers are stopped by having the
scheduler call retire_workers when we stop a worker.

### CODE REVIEW

**Comment by TomAugspurger** [comment]
@mrocklin could I bug you to glance at this when you get a chance? No rush.

The only complication was the difference in worker keys between `DRMAACluster` (job ids) and the scheduler (IP addresses). Is that information already stored anywhere on the cluster? For now I just run a small function on the worker to get the IP address when we go to stop a worker.

**Comment by mrocklin** [comment]
The scheduler should have the names of all of the workers' addresses.  This is the key that indexes every collection on the scheduler about the workers.  I believe that a `DRMAACluster` *has* a local scheduler already within its LocalCluster object.  You shouldn't need to communicate to the scheduler remotely.

```python
In [1]: from dask.distributed import LocalCluster

In [2]: cluster = LocalCluster()


In [4]: list(cluster.scheduler.worker_info)
Out[4]: 
['tcp://127.0.0.1:32803',
 'tcp://127.0.0.1:43528',
 'tcp://127.0.0.1:34939',
 'tcp://127.0.0.1:34041']
```

I may not fully understand the situation though

**Comment by TomAugspurger** [comment]
I think the issue is that the  `worker_ids` argument to `stop_workers` are
the Job IDs like:


```python
In [5]: cluster.workers.keys()
Out[5]: dict_keys(['585.1', '585.2'])
```

So I need to translate from those to IP addresses of the workers that the
scheduler uses.

**Comment by mrocklin** [comment]
My solution to this problem was to just never depend on job ids and instead
ask the scheduler to remove workers itself.

Alternatively you might supply the JobID as the alias of the worker with
the --name keyword

**Comment by TomAugspurger** [comment]
> Alternatively you might supply the JobID as the alias of the worker with
the --name keyword

Turns out you already had that good idea. The changes here seem to have introduced a race condition that I'll try to debug later today.

**Comment by TomAugspurger** [comment]
Apologies for the delay on this. It took longer than expected for me to identify the race condition.

**Pull request merged**
