### PR TITLE
Add a basic manifest to aid in packaging

### PR DESCRIPTION
**Pull request by jakirkham**
Make sure the LICENSE and README are included. Also ensure any compiled Python code is not included.

### CODE REVIEW

**Comment by jakirkham** [comment]
Any thoughts on this?

**Comment by mrocklin** [comment]
Fine with me

**Comment by mrocklin** [comment]
As an FYI this project is not a high priority for me personally at the
moment, so feedback from me may be brief generally.

**Comment by jakirkham** [comment]
Make sense. Is alright if I merge small PRs like this at my own discretion then?

**Comment by mrocklin** [comment]
Definitely :)

**Comment by jakirkham** [comment]
Great, thanks. 😄

**Comment by jakirkham** [comment]
Would it be possible to disable merging with a merge commit and/or make merge squash the default for this repo?

**Comment by mrocklin** [comment]
Fine with me

**Comment by jakirkham** [comment]
So I lack the permissions to do this myself. Would you be able to change that or could I have permissions to do that?

**Comment by mrocklin** [comment]
I've disabled the merge-commit option.  I'm not sure how to fine-tune permissions like this.  There's always the option to give everyone admin privileges, which might be reasonable.  That would probably require a larger conversation including more of the current core contributors.

**Comment by jakirkham** [comment]
Thanks for doing that. No worries.

**Pull request merged**
