### PR TITLE
Check for slurm earlier in the process

### PR DESCRIPTION
**Pull request by jcftang**
This relates to https://github.com/dask/dask-drmaa/pull/33

### CODE REVIEW

**Comment by jcftang** [comment]
I just moved the changes to the create job templates method as suggested in #33 comments

**Comment by jakirkham** [comment]
Toggling for CI.

**Comment by jakirkham** [comment]
This replaces PR ( https://github.com/dask/dask-drmaa/pull/33 ), right? If so, do you mind adding a "Closes" statement in the OP?

**Comment by jakirkham** [comment]
Sorry to be so slow getting back to this. Also thanks for raising this. Have a similar issue with LSF.

Thinking about this a bit. I wonder if we shouldn't just make the job id environment variable name a configurable parameter of the `DRMAACluster` instead. That should improve flexibility if users want to add more information into the out/err filenames of the workers and better handle the different clusters people are using dask-drmaa on. Thoughts?

**Comment by mrocklin** [comment]
Making this user overrideable sounds nice

**Comment by jakirkham** [comment]
Trying to more generally address this in PR ( https://github.com/dask/dask-drmaa/pull/56 ). Feedback and help testing would be appreciated.

**Pull request closed without merging**
