### PR TITLE
Make sure, script is abspath, fixes #87

### LINKED ISSUE #87: Give absolute path to worker script
Starting workers fails (at least on slurm) if the `template['workingDirectory']` is not the current working directory because:

```
/var/spool/slurm/d/job1177731/slurm_script: line 2: ./dask-worker-scriptz8gmf_cpsh: No such file or directory
```

### PR DESCRIPTION
**Pull request by MaxNoe**
I also added the possibility to set the directory in which the scripts are saved

### CODE REVIEW

**Comment by jakirkham** [comment]
Is it alright if we discuss the `script_dir` in a separate issue first? Would like to keep this scoped to the bug fix for now.

**Comment by jakirkham** [comment]
Also any thoughts on an accompanying test?

**Comment by MaxNoe** [comment]
ok, I'll remove the last commit.

**Comment by MaxNoe** [comment]
I removed the last commit @jakirkham

**Pull request merged**
